openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /auth/signup:
    post:
      summary: User signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                login:
                  type: string
                password:
                  type: string  
      responses:
        201:
          description: User created
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
      responses:
        201:
    /auth/user:
    get:
      summary: Get all users
      responses:
        200:
          description: Returns a list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    surname:
                      type: string
                    login:
                      type: string
            

